project_name: date_gap_finder
build:
  main: .
  binary: date_gap_finder
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
  goarm:
      - 7
  ignore:
    - goos: windows
      goarch: arm
      goarm: 7
    - goos: windows
      goarch: arm
      goarm: 6
archives:
    - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
      format: tar.xz
      format_overrides:
        - goos: windows
          format: zip
      replacements:
          darwin: macOS
      wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"
release:
  draft: true
